language: go
go:
  - "1.14.4"
script:
  - go build
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash travis/deploy.sh; fi'
addons:
  ssh_known_hosts:
    - 159.89.210.122
    - 139.59.216.161